emr/urls.py
from django.urls import path,re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.user_login, name="login"),
    re_path(r'^logout/?$', views.logout, name="logout"),
    re_path(r'^change_password/?$', views.change_password, name="change_password"),
    path('reset_password/', views.reset_password, name='reset_password'),
    re_path(r'^secure/?$', views.dashboard, name="dashboard"),
    re_path(r'^staff/search/?$', views.search_staff, name="search_staff"),
    path('staff/<int:id>/', views.view_staff, name='view_staff'),
    re_path(r'^staff/add_staff/?$', views.add_staff, name="add_staff"),
    
    re_path(r'^patients/?$', views.get_patients, name="get_patients"),
    path("patient/search", views.search_patient, name="search_patient"),
    re_path(r'^patients/(?P<user_id>\d+)/?$', views.get_patient, name="get_patient"),
    path("patients/register-card/", views.register_search_card, name="register_search_card"),
    re_path(r'^patients/register/?$', views.add_patient, name="register_patient"),
    re_path(r'^patients/(?P<user_id>\d+)/edit/?$', views.update_patient, name="update_patient"),
    re_path(r'^add_vital/(?P<appointment_id>\d+)/?$', views.add_vital, name="add_vital"),
    re_path(r'^add_vital/?$', views.appointments),
    
    path("add_vital/<int:appointment_id>/<int:patient_id>", views.add_vital, name="add_vital"),
    re_path(r'^appointments/?$', views.appointments, name="appointments"),
    re_path(r'^appointments/(?P<user_id>\d+)/?$', views.book_appointment, name="book_appointment"),
    re_path(r'^appointments/(?P<user_id>\d+)/(?P<appointment_id>\d+)/?$', views.book_appointment_doctor, name="book_appointment_doctor"),
    path('appointments/scheduled', views.scheduled_appointments, name='scheduled_appointments'),

     
    path('billing/', views.home),
    re_path(r'^billing/payments/?$', views.payments, name="payment_history"),
    path('billing/consultation/<str:status>/', views.consultation_payments, name='consultation_payments'),
    path('billing/lab/<str:status>/', views.lab_payments, name='lab_payments'),
    path('billing/pharmacy/<str:status>/', views.drug_payments, name='drug_payments'),
    path('billing/confirm/<int:billing_id>/', views.confirm_appointment_payment, name='confirm_appointment_payment'),
    path('billing/confirm-drug/<int:order_id>/', views.confirm_drug_payment, name='confirm_drug_payment'),
    path('billing/invoice/<int:qid>/', views.invoice, name='invoice'),
    path('billing/card-registration/', views.card_registration_payment, name='pay_card'),
    path('billing/card-renewal/', views.card_renewal_payment, name='card_renewal_payment'),
    path('billing/add-card-price/', views.add_card_price, name='add_card_price'),
    path("billing/card/search", views.card_payment_search, name="card_payment_search"),
    path("billing/income-stream/create", views.create_income_stream, name="create_income_stream"),
    path("billing/income-streams", views.income_streams, name="income_streams"),
    path("billing/income-streams/record", views.record_income_stream, name="record_income_stream"),
    path("billing/income-streams/search", views.view_income_stream, name="view_income_stream"),
    path("billing/income-streams/show", views.view_income_stream_from_range, name="view_income_stream_from_range"),
    re_path(r'^billing/confirm_payment/?$', views.confirm_payment, name="confirm_payment"),
    
    path("account/income/action", views.approve_income, name="approve_income"),
    
    
    

    
    
    path('lab/', views.home),
    path('lab/add_lab_results/<int:id>/', views.add_lab_result, name='add_lab_result'),
    path('lab/view_result/<int:test_id>/', views.view_lab_result, name='view_lab_result'),
    re_path(r'^lab/lab_results/?$', views.lab_results, name="lab_results"),
    path('lab/add_lab_test/<int:user_id>/', views.add_lab_test, name='add_lab_test'),
    path('lab/lab_test/<int:user_id>/', views.patient_lab_tests, name='patient_lab_tests'),
    path('lab/add_lab_price/', views.add_lab_price, name='add_lab_price'),
    path('lab/view_lab_price/', views.lab_prices, name='lab_prices'),
    re_path(r'^lab/lab_tests/?$', views.lab_list, name="lab_tests"),
    
    path('doctor/', views.home),
    re_path(r'^doctor/appointments/?$', views.appointments, name="doctor_appointments"),
    re_path(r'^doctor/prescriptions/(?P<user_id>\d+)/?$', views.prescriptions, name="prescriptions"),
    re_path(r'^doctor/prescriptions/(?P<user_id>\d+)/(?P<prescription_id>\d+)/?$', views.prescription, name="prescription"),
    path('doctor/prescriptions/create/<int:user_id>/<int:appointment_id>', views.add_prescription, name="add_prescription"),
    
    
    path('pharmacy/', views.home),
    re_path(r'^pharmacy/drugs/?$', views.drug_list, name="drugs"),
    re_path(r'^pharmacy/add_drug/?$', views.add_drug, name="add_drug"),
    path('pharmacy/update_drug/<int:d_id>/', views.update_drug, name='update_drug'),
    re_path(r'^pharmacy/drug_sell/?$', views.drug_sell, name="sale_drug"),
    # re_path(r'^pharmacy/sale_drug/?$', views.sale_drug, name="sale_drug"),
    path('pharmacy/prescribed', views.prescribe_drug, name="prescribed_drug"),
    path('pharmacy/prescribed_drugs/<int:prescription_id>/', views.view_prescribed_drug, name="view_prescribed_drugs"),
    re_path(r'^pharmacy/sale_drug/?$', views.sale_drug, name="sale_drug"),
    path('pharmacy/get_drug_details/', views.get_drug_details, name="get_drug_details"),
    path('pharmacy/drug_history/', views.drugs_history, name="drugs_history"),
    path('pharmacy/history_detail/<int:order>/', views.drug_history_detail, name="drug_history_detail"),
    
    
    
    path('report/generate', views.generate_bill_report, name="generate_bill_report"),
    path('report/generate/result', views.generated_bill_report, name="generated_bill_report"),
    
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emr.urls'))
]


handler404 = 'emr.views.custom_404'

emr/models.py
import random
import time
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField

from emr.utils import ethnic_groups



class Department(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
class Staff(AbstractUser):
    phone_number = models.CharField(max_length=20)
    updated_at = models.DateTimeField(auto_now=True)
    department = models.ForeignKey("Department",on_delete=models.CASCADE, null=True, default=None)
    doctor_type = models.CharField(max_length=100, null=True, blank=True)  # contract or permanent
    doctor_specialization = models.CharField(max_length=100, null=True, blank=True)
    is_chief_consultant = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_store_keeper = models.BooleanField(default=False)
    is_hod = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30, blank=False)
    last_name = models.CharField(max_length=150, blank=False)
    
    # Define related_name for groups and user_permissions
    # Make groups nullable
    groups = models.ManyToManyField(
        Group,
        related_name='staff_users',
        blank=True,  # Allow blank values
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_('user permissions'),
        blank=True,
        related_name='staff_users',
        help_text=_('Specific permissions for this user.'),
    )


    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    def save(self, *args, **kwargs):
        if not self.pk:  # Only set the password if the user is being created (not updated)
            # Set the default password
            self.set_password('password1')  
        
        # Generate the username based on the count of existing Staff objects with "CBH" prefix
        if not self.username:
            prefix = "CBH"
            count = Staff.objects.filter(username__startswith=prefix).count() + 1
            self.username = f"{prefix}{count:03d}"  # Zero-padded 3-digit count
        
        super().save(*args, **kwargs)



class Patient(models.Model):
    MARRIAGE_STATUS = (
        ('single', 'Single'),
        ('married', 'Married'),
        ('divorced', 'Divorced'),
        ('widow', 'Widow(er)'),
    )
    PATIENT_TYPE = (
        ('in-patient', 'In-Patient'),
        ('out-patient', 'Out-Patient'),
        ('emergency', 'Emergency')
    )
    
    RELIGION = (
        ('christainity', 'Christianity'),
        ('islam', 'Islam'),
        ('tradional', 'Tradional'),
        ('judaism', 'Judaism'),
        ('other', 'Other'),
    )
    
    ETHIC_GROUP = ethnic_groups()
    
    GENDER = (
        ('male', 'Male'),
        ('female', 'Female')
    )
    
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dob = models.DateField()
    card_number = models.ForeignKey("Card",on_delete=models.CASCADE)
    next_of_kin = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=20)
    doctor = models.ForeignKey("Staff",on_delete=models.CASCADE, null=True, default=None)
    registrar = models.ForeignKey("Staff", related_name="registrar", on_delete=models.CASCADE, null=True, default=None)
    address_of_kin = models.CharField(max_length=200, null=True, blank=True)
    place_of_origin = models.CharField(max_length=100)
    marriage_status = models.CharField(max_length=50, choices=MARRIAGE_STATUS)
    patient_type = models.CharField(max_length=50, choices=PATIENT_TYPE)
    gender = models.CharField(max_length=50, choices=GENDER)
    next_of_kin_phone = models.BigIntegerField(null=True, blank=True)
    ethnic_group = models.CharField(max_length=100, choices=ETHIC_GROUP)
    occupation = models.CharField(max_length=100)
    religion = models.CharField(max_length=100, choices=RELIGION)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name} "
    


class Billing(models.Model):
    SERVICE_TYPES = (
        ('Consultation', 'Consultation'),
        ('LabTest', 'Lab Test'),
        ('XRay', 'X-Ray'),
        ('DrugSale', 'Drug Sale'),
        ('NewCard', 'New Card'),
        ('CardRenewal', 'Card Renewal')
    )
    METHOD = (
        ('cash', 'Cash'),
        ('transfer', 'Transfer'),
       
    )

    service_type = models.CharField(max_length=20, choices=SERVICE_TYPES)
    service_id = models.ForeignKey('Appointment', on_delete=models.CASCADE, null=True, blank=True)
    sold_drug = models.ForeignKey('SoldDrug', on_delete=models.CASCADE, null=True, blank=True)
    card = models.ForeignKey('Card', on_delete=models.CASCADE, null=True, blank=True)
    is_card_renewal = models.BooleanField(default=False)
    invoice_id = models.BigIntegerField(null=True, blank=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    payment_method = models.CharField(max_length=20, choices=METHOD, null=True, blank=True)
    payment_status = models.BooleanField(default=False)
    payment_date = models.DateField(null=True, blank=True)
   

class IncomeStream(models.Model):
    name = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f"{self.name}"


class IncomeRecord(models.Model):
    income_stream = models.ForeignKey(IncomeStream, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ref_code = models.BigIntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.income_stream}"
    
class ApprovedIncomeRecord(models.Model):
    ref_code = models.ForeignKey(IncomeRecord, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    created_at = models.DateField(auto_now_add=True)


class CardPrice(models.Model):
    TYPES = (
        ('new', 'New Card'),
        ('renew', 'Card Renewal'),
    )
    card_type = models.CharField(max_length=20, choices=TYPES)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.BooleanField(default=True)  # Set default value to True
    
    def __str__(self):
        return self.card_type
    


class Card(models.Model):
    card_number = models.BigIntegerField()
    is_expired = models.BooleanField(default=False)
    expiration_date = models.DateField(null=True, blank=True)
    
    def __str__(self):
        return str(self.card_number)

   
class Appointment(models.Model):
    
    APPOINTMENT_TYPE_CHOICES = [
        ('Consultation', 'Consultation'),
        ('LabTest', 'Lab Test'),
        ('XRay', 'X-Ray'),
        
    ]
    
    
    patient = models.ForeignKey('Patient', related_name='appointments', on_delete=models.CASCADE)
    doctor = models.ForeignKey('Staff', on_delete=models.CASCADE, null=True, blank=True)
    labprice = models.ForeignKey('labPrice', on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=1, default=0)
    appointment_date = models.DateTimeField(auto_now_add=True)
    appointment_type = models.CharField(max_length=100, choices=APPOINTMENT_TYPE_CHOICES)
    
    def save(self, *args, **kwargs):
        is_new = not self.pk  # Check if the object is being created for the first time
        super().save(*args, **kwargs)

        if is_new:
            Billing.objects.create(
                service_type=self.appointment_type,
                service_id=self,
                payment_status=False,
            )

            # Create LabTest record only if the appointment type is 'LabTest'
            if self.appointment_type == 'LabTest' and self.labprice:
                LabTest.objects.create(
                    patient=self.patient,
                    name=self.labprice,
                    appointment=self
                )

    def __str__(self):
        return f"{self.patient}"
    
    
class VitalSigns(models.Model):
    appointment = models.ForeignKey('Appointment', related_name='vitalsigns', on_delete=models.CASCADE)
    pulse_rate = models.FloatField(max_length=12)
    blood_pressure = models.FloatField(max_length=12, null=True,blank=True)
    temperature = models.FloatField(max_length=12, null=True,blank=True)
    weight = models.FloatField(max_length=12, default=0)
    nurse = models.ForeignKey('Staff', on_delete=models.CASCADE, related_name='nurse_vitalsigns')
    doctor = models.ForeignKey('Staff', on_delete=models.CASCADE, null=True, blank=True, related_name='doctor_vitalsigns')
    note = models.TextField(null=True,blank=True)
    
    

class labPrice(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
         return f"{self.name}"



class LabTest(models.Model):    
    patient = models.ForeignKey('Patient',  on_delete=models.CASCADE)
    name = models.ForeignKey('labPrice',  on_delete=models.CASCADE)
    appointment = models.ForeignKey('Appointment', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.name}"



class LabResult(models.Model):
    test = models.ForeignKey('LabTest', on_delete=models.CASCADE)
    file_name = models.FileField(upload_to='static/labresults/', blank=True, null=True)
    result = RichTextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f"{self.result}" 
    




class Drug(models.Model):

emr/templates/lab/add_lab_price.html
{% extends "main.html" %}

{% load static %}

{% block 'content' %}
      <!-- theme body start-->
      <div class="theme-body common-dash" data-simplebar="">
        <div class="container-fluid">
          <div class="row">        
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <h4>Add Lab Test Price</h4>
                </div>
                <div class="card-body"> 
                  {% if messages %}
                  <div class="messages">
                      {% for message in messages %}
                      <div class="alert alert-{{ message.tags }}">
                          {{ message }}
                      </div>
                      {% endfor %}
                  </div>
                {% endif %}
                {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                        <li>{{ field|title }}: {{ error }}</li>
                        {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                  <form method="POST">
                    {% csrf_token %}
                    <div class="row">

             
                      <div class="form-group col-md-6">
                        <div class="form-label">Test Name</div>
                        {{ form.name }}
                      </div>
                      <div class="form-group col-md-6">
                        <div class="form-label">Price</div>
                        {{ form.price }}
                      </div>

                      <div class="form-group text-end mb-0">          
                          <button class="btn btn-sm btn-primary" type="submit" >Submit</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- theme body end-->
 
{% endblock 'content' %}

emr/templates/lab/add_lab_result.html
{% extends "main.html" %}

{% load static %}

{% block 'content' %}
      <!-- theme body start-->
      <div class="theme-body common-dash" data-simplebar="">
        <div class="container-fluid">
          <div class="row">        
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <h4>Upload Result</h4>
                </div>
                <div class="card-body"> 
                  {% if messages %}
                  <div class="messages">
                      {% for message in messages %}
                      <div class="alert alert-{{ message.tags }}">
                          {{ message }}
                      </div>
                      {% endfor %}
                  </div>
                {% endif %}
                {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                        <li>{{ field|title }}: {{ error }}</li>
                        {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                {% if exist %}
                  <div>
                      <div class="alert alert-info">Result Has Been Uploaded</div>
                  </div>
                {% else %}
                  <div class="col-md-4 form-group ">
                    <select id="select" class="form-control">
                      <option value="">Select Upload Medium</option>
                      <option value="file">File</option>
                      <option value="type">Type</option>
                    </select>
                  </div>
                {% endif %}
                  <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">

                      <div class="form-group col-md-12">
                        <div class="form-label">Test</div>
                        <select name="test" id="" class="form-control" readonly>
                            <option value="{{ test.id }}">{{ test }}</option>
                        </select>
                      </div>

                      

                      <div class="form-group col-md-12 d-none" id="result_file" >
                        <div class="form-label">Upload File</div>
                        {{ form.file_name }}
                      </div>
                      

                      <div class="form-group col-md-12 d-none" id="type">
                        <div class="form-label">Enter Result</div>
                        {{ form.media }}
                        {{ form.result }}
                      </div>

                      

                      <div class="form-group text-end mb-0 d-none" id="button" >          
                          <button class="btn btn-sm btn-primary" type="submit" >Submit</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- theme body end-->

      <script>
        $("#select").change(function(){
           var select = $(this).val();
           if(select == "file") {
             $("#result_file").removeClass('d-none')
             $("#button").removeClass('d-none')
             $("#type").addClass('d-none')
           } else if(select == "type") {
              $("#type").removeClass('d-none')
              $("#button").removeClass('d-none')
              $("#result_file").addClass('d-none')
           } else{
            $("#type").addClass('d-none')
            $("#result_file").addClass('d-none')
            $("#button").addClass('d-none')
           }
        })
      </script>
 
{% endblock 'content' %}

emr/templates/lab/add_lab_test.html
{% extends "main.html" %}

{% load static %}

{% block 'content' %}
      <!-- theme body start-->
      <div class="theme-body common-dash" data-simplebar="">
        <div class="container-fluid">
          <div class="row">        
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <h4>Register Test</h4>
                </div>
                <div class="card-body"> 
                  {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                        {% endfor %}
                    </div>
                  {% endif %}
                  {% if form.errors %}
                  <div class="alert alert-danger">
                      <ul>
                          {% for field, errors in form.errors.items %}
                          {% for error in errors %}
                          <li>{{ field|title }}: {{ error }}</li>
                          {% endfor %}
                          {% endfor %}
                      </ul>
                  </div>
                  {% endif %}
                  <form method="post">
                    {% csrf_token %}
                    <div class="row">

                      <input type="hidden" name="patient" value="{{ patient.id }}" hidden>

                      <div class="form-group col-md-4">
                          <div class="form-label">Title</div>
                          <select name="name" class="form-control">
                            <option value="">Select a Lab Test</option>
                            {% for name in form.name.field.queryset %}
                                <option value="{{ name.id }}">{{ name }} - {{ name.price }}</option>
                            {% endfor %}
                        </select>
                      </div>
                        
                      <div class="form-group text-end mb-0">          
                          <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                      </div>

                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- theme body end-->
 
{% endblock 'content' %}

emr/templates/lab/lab-list.html
{% extends "main.html" %}

{% load static %}

{% block 'content' %}
  <!-- theme body start-->
      <div class="theme-body codex-chat">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              <div class="card">  
                <div class="card-body">
                  <table class="doctorslist-tbl table" id="doctorslist-tbl" style="width:100%;">
                    <thead>
                      <tr>
                        <th>S/N</th>
                        <th>Patient</th>
                        <th>Test Title</th>
                        <th>Status</th>
                        <th>Test Date</th>
                        <th>Result</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                      {% for test in tests %}
                      <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ test.patient }} </td>
                        <td> {{ test.name }} </td>
                        <td> 

                           {% if test.appointment.status == '1' %}
                            <span class="badge badge-success">Paid</span>
                            {% else%}
                            <span class="badge badge-danger">UnPaid</span>
                            {% endif %}
                        </td>
                        <td> {{ test.created_at }} </td>
                        <td>
                          {% if test.labresult_set.exists %}
                              <a href="{% url 'view_lab_result' test.id %}" class="btn btn-primary">View Result</a>
                          {% else %}
                          {% if test.appointment.status == '1' %}
                              <a href="{% url 'add_lab_result' test.id %}" class="btn btn-primary">Add Result</a>
                              {% else%}
                              -
                            {% endif %}
                          {% endif %}
                        </td>
                      </tr>
                      {% endfor %}
                     

                    </tbody>
                  </table>
                </div>
               
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock 'content' %}

emr/templates/lab/lab-prices.html
{% extends "main.html" %}

{% load static %}

{% block 'content' %}
  <!-- theme body start-->
      <div class="theme-body codex-chat">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              <div class="card">  
                <div class="card-body">
                  <table class="doctorslist-tbl table" id="doctorslist-tbl" style="width:100%;">
                    <thead>
                      <tr>
                        <th>S/N</th>
                        <th>Test Caption</th>
                        <th>Price</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for test in tests %}
                      <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ test.name }} </td>
                        <td> <strike>N</strike>{{ test.price }} </td>
                      </tr>
                      {% endfor %}
                     

                    </tbody>
                  </table>
                </div>
               
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock 'content' %}

emr/templates/lab/patient-lab-list.html
{% extends "main.html" %}

{% load static %}

{% block 'content' %}
  <!-- theme body start-->
      <div class="theme-body codex-chat">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              <div class="card">  
                <div class="card-body">
                    <h4 class="title text-muted">{{ name }} - Lab Test Record</h4>
                  <table class="doctorslist-tbl table" id="doctorslist-tbl" style="width:100%;">
                    <thead>
                      <tr>
                        <th>S/N</th>
                        <th>Test Title</th>
                        <th>Status</th>
                        <th>Test Date</th>
                        <th>Result</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for test in tests %}
                      <tr>
                        <td> {{ forloop.counter }} </td>
                        <td> {{ test.name }} </td>
                        <td> 
                           {% if test.appointment.status %}
                            <span class="badge badge-success">Paid</span>
                            {% else%}
                            <span class="badge badge-danger">UnPaid</span>
                            {% endif %}
                        </td>
                        <td> {{ test.created_at }} </td>
                        <td>
                          {% if test.labresult_set.exists %}
                              <a href="{% url 'view_lab_result' test.id %}" class="btn btn-primary">View Result</a>
                          {% else %}
                              <a href="{% url 'add_lab_result' test.id %}" class="btn btn-primary">Add Result</a>
                          {% endif %}
                        </td>
                      </tr>
                      {% endfor %}
                     

                    </tbody>
                  </table>
                </div>
               
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock 'content' %}